site: notes
url: https://notes.velitasali.com
title: notes
description: english literature studies by veli tasalı et al.
baseurl: ""

owner:
  name: Veli Tasalı
  email: me@velitasali.com
  twitter: velitasali
  github: velitasali
  url: https://velitasali.com
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

permalink: pretty
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  authors:
    output: true

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
