site: notes
url: https://notes.velitasali.com
title: notes
description: english literature studies by veli tasalı et al.
permalink: pretty
baseurl: ""

owner:
  name: Veli Tasalı
  email: me@velitasali.com
  twitter: velitasali
  github: velitasali
  url: https://velitasali.com

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-feed
  - jekyll-seo-tag  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  authors:
    output: true
  
tag_page_layout: tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"